### ISSUE TITLE
Change the Curstain state on the Park telescope

### ISSUE THREAD

**Issue by spider65** [ara-astronomia/AutomazioneTende#84]
Now the status of the curtains when the telescope is sent in the park position is different if the command comes from Crac or TheSkyX.
It is necessary that the curtains assume the same position both if the park is called by thesky or by crac.
This command must bring the telescope to the park position, set the tracking off and close the curtains

**Comment by alkcxy** [comment]
We should take care of the consequences of all the possible options.
1 - Close the curtains: if a user want to go upstairs to manage somehow the telescope could be useful to keep the curtains open up.
2 - Open up the curtains: good for a user that wants to go to the telescope, but if he's closing the observatory we are slowing down the operation because the curtains first open all up and then when we deactivate them, they should be brought down before close the roof.
